### ISSUE TITLE
Skjule enkeltema

### ISSUE THREAD

**Issue by raae** [lesersokerbok/lsb-wordpress-themes#97]
Skjule tema (lsb_tax_topic) for besøkene slik at det ikke blir for mye støy for besøkende, men la dem være i backend slik at de gir treff i søk.

**Comment by raae** [comment]
Legge inn et valg med adcf som skrur av/på visning.

**Comment by raae** [comment]
Kunnde du tatt en titt på denne @

**Comment by schikulski** [comment]
Dette er da altså pr. emne? F.eks. at man kan velge om emnet historie skal vises for besøkende eller ikke?

**Comment by raae** [comment]
Ja, det stemmer.

Den fredag 3. juli 2015 skrev Simen Schikulski <notifications@github.com>
følgende:

> Dette er da altså pr. emne? F.eks. at man kan velge om emnet historie skal
> vises for besøkende eller ikke?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lesersokerbok/lsb-wordpress-themes/issues/97#issuecomment-118282274>
> .
>


-- 
Benedicte | Lilly Labs <http://lillylabs.no> | 97667045

**Comment by schikulski** [comment]
Da har jeg commitet et forslag på develop-branchen! Rop ut om du heller vil ha det i egen feature-branch uten at den er merga til develop, forresten. Gikk ut i fra at dette ikke var en _larger feature branches_ :)

**Comment by raae** [comment]
Ser bra ut :D Vi begynte å gjøre strenger oversettbare, så jeg fikset opp i det.
